version: '3.8'
services:
    next:
        build: ./
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        volumes:
            - ./:/app/
            - /app/node_modules
